import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const base = `HUSTLE,DRIVEN,COMMIT,GROWTH,TARGET,REWARD,HABITS,VISION,LAUNCH,IMPACT,OUTPUT,SYSTEM,REVIEW,SPRINT,DEPLOY,METRIC,SIGNAL,RHYTHM,FILTER,BELIEF,COURAG,MINDFU,RESILN,FOCUSD,GRATEF,POSITI,CONFID,EMPOWE,ACCEPT,CURIOU,EVOLVE,THRIVE,MASTER,CREATE,MILEST,ACHIEV,SUCCES,FULFIL,PURSUE,CONQUE,STRIVE,ASPIRE,EXCELL,LEADRN,ENERGY,BREATH,SLEEPS,MOVEMT,BALNCE,RECVRY,NUTRIT,ACTIVE,MINDSET`
  .split(",")
  .map((s) => s.trim().toUpperCase())
  .filter((w) => w.length === 6);

const fill = `ACTION,RESULT,SIMPLE,CHOOSE,DECIDE,FINISH,BEFORE,AFFIRM,CHARGE,MATTER,LEADER,WINDOW,BRIDGE,STEADY,LISTEN,CENTER,FRIEND,FUTURE,NUMBER,OBJECT,SUBTLE,GENTLE,WISDOM,BORDER,REASON,SEASON,ANCHOR,BEACON,PLAYER,CUSTOM,FORMAT,DRIVER,SERVER,CLIENT,INPUTS,POCKET,ROCKET,MARKET,BASKET,BULLET,WALLET,STRONG,BETTER,FASTER,SMART,CLEVER,BRIGHT,SQUARE,CIRCLE,WEIGHT,HEIGHT,LIGHTS,SECOND,MINUTE,ONLINE,POLICY,OFFICE,BUTTON,PANELS,TICKET,SOCKET,REPEAT,REPORT,RETURN,REVEAL,SAMPLE,SEARCH,SECRET,SECURE,SELECT,SENDER,SENIOR,SILENT,SILVER,SINGLE,SISTER,SKETCH,SLIGHT,SMOOTH,SOCIAL,SOLVER,SOUNDS,SOURCE,SPACES,SPHERE,SPREAD,SPRING,STABLE,STAGES,STAIRS,STATUS,STONES,STREAM,STREET,STRIKE,STUDIO,SUDDEN,SUMMIT,SUPPLY,SURELY,SURVEY,SURVIVE,SWITCH,SYMBOL,TALENT,TEMPLE,TENANT,TENNIS,TIMING,TOGGLE,TOWARD,TRAVEL,TRENDS,TRIBAL,TRIPLE,TROPHY,TUNNEL,TURTLE,UNIQUE,UNISON,UNITED,UNPACK,UPDATE,UPLOAD,UPWARD,URGENT,USEFUL,VACUUM,VALLEY,VALUED,VECTOR,VELVET,VENDOR,VERIFY,VERSUS,VESSEL,VICTOR,VIRTUE,VISIBLE,VOLUME,WALKER,WANTED,WARMTH,WEALTH,WIDGET,WINTER,WONDER,WORKER,WORTHY,YELLOW,YIELD,ABOARD,ABSENT,ACCEPT,ACCESS,ACCENT,ACCUSE,ACROSS,ACTIVE,ACTUAL,ADVICE,ADVISE,AFFAIR,AFFECT,AFFORD,AFRAID,AGENCY,AGENDA,ALMOST,ALWAYS,AMOUNT,ANIMAL,ANNUAL,ANSWER,ANYONE,ANYWAY,APPEAR,AROUND,ARRIVE,ARTIST,ASPECT,ASSESS,ASSIGN,ASSIST,ASSUME,ASSURE,ATTACH,ATTACK,ATTEND,AUTHOR,AVOID,AWARD,BOTTOM,BRANCH,BREATH,BUDGET,BUFFER,CAMERA,CAPABLE,CAPITAL,CAPTURE,CAREER,CHANCE,CHANGE,CHURCH,CIRCLE,CITIZN,CLEARS,CLOSED,COACH,COMBAT,COMING,COMMON,COMPNY,CONCEPT,CONCERN,CONDUCT,CONFIRM,CONNECT,CONSENT,CONSIST,CONTACT,CONTAIN,CONTENT,CONTEXT,CONTROL,CONVERT,COOKIE,CORNER,COSTLY,COUNT,COUNTRY,COURSE,COVER,CREAM,CREATE,CREDIT,CRISIS,CULTURE,CURRENT,CUSTOM,CYCLE,DAMAGE,DANGER,DEALER,DEGREE,DELIVER,DEMAND,DEPEND,DESIGN,DESIRE,DETAIL,DETECT,DEVICE,DIFFER,DINNER,DIRECT,DOCTOR,DOUBLE,DRAWER,DURING,EASILY,EDITOR,EFFECT,EFFORT,EIGHTH,EITHER,ELEVEN,EMERGE,ENABLE,ENGAGE,ENGINE,ENOUGH,ENSURE,ENTIRE,ENTITY,EQUITY,ESCAPE,ESSAY,ESTATE,ETHICS,EVENT,EXPORT,EXTEND,EXTENT,FABRIC,FACING,FAILED,FAIRLY,FALLEN,FAMILY,FAMOUS,FATHER,FEATURE,FIGURE,FINGER,FLAVOR,FLIGHT,FLOWER,FOLLOW,FOREST,FORGET,FORMAL,FORMER,FOSTER,FOUGHT,FOURTH,FREELY,GARDEN,GATHER,GENDER,GLOBAL,GOLDEN,GOVERN,GRADUAL,GRAVEL,GREATER,HANDLE,HAPPEN,HARBOR,HEALTH,HIDDEN,HOLDER,HONEST,HORROR,HOUSING,HUMBLE,HUNTER,IMAGINE,IMPORT,INCOME,INDEED,INDOOR,INITIAL,INJURY,INSIDE,INSTALL,INTEND,INTENT,INVEST,ISLAND,JACKET,JUNIOR,KEEPER,KITCHEN,LADDER,LARGER,LATEST,LAWYER,LAYOUT,LEAGUE,LEARN,LENGTH,LESSON,LETTER,LEVEL,LIGHT,LIMIT,LIQUID,LITTLE,LIVING,LOCAL,LOCATE,LOCKER,LOGICAL,LOVELY,LOWEST,LUMBER,MAGNET,MAINLY,MAKING,MANAGE,MANNER,MANUAL,MARGIN,MATRIX,MAXIMUM,MEANING,MEDIUM,MEMBER,MEMORY,MENTAL,METHOD,MIDDLE,MIGRATE,MINIMAL,MIRROR,MOBILE,MODERN,MODULE,MOMENT,MOTHER,MOUNT,MUSCLE,MUSEUM,MUTUAL,NARROW,NATION,NATIVE,NATURE,NEARBY,NEEDLE,NEITHER,NERVOUS,NETWORK,NEUTRAL,NOTION,OBJECT,OCCUPY,OPTION,ORANGE,ORIGIN,OXFORD,PACKET,PALACE,PARENT,PARTLY,PARTNER,PASSAGE,PATENT,PATROL,PATTERN,PAYING,PENCIL,PEOPLE,PERIOD,PERMIT,PERSON,PHASE,PHONE,PHOTO,PICKED,PIECE,PILOT,PIONER,PLACED,PLANET,PLASTIC,PLEASE,PLENTY,PORTAL,POSTER,POTATO,POWDER,POWER,PRAISE,PREFER,PRETTY,PRICED,PRINCE,PRISON,PRIVATE,PROFIT,PROMPT,PROPER,PROVEN,PUBLIC,PYTHON,QUALFY,QUARTZ,QUIET,RADIAL,RADIUS,RAISED,RANDOM,RAPID,RATHER,READER,REALLY,RECALL,RECENT,RECORD,REDUCE,REFORM,REFUSE,REGION,RELATE,RELIEF,REMAIN,REMIND,REMOTE,REMOVE,RENDER,REPAIR,RESCUE,RETAIL,RETAIN,RETIRE,RHYTHM,RIDING,RISING,ROBUST,ROUTER,RUBBER,RUGGED,RULING,RUNNER,SACRED,SADDLE,SALARY,SCALES,SCHEME,SCHOOL,SCREEN,SCRIPT,SECTOR,SETTLE,SEVERE,SHADOW,SHARED,SHELF,SHIELD,SHOULD,SHOWER,SMARTY,SMILED,SOFTER,SOLIDS,SORTED,SPARKS,SPLITS,SPORTS,STARED,STOLEN,STORED,STRAPS,STRESS,STRICT,STRIPE,STROKE,SUBWAY,SUGARS,SUITED,SUNSET,SUPPER,SURFER,SWATCH,SWEETS,TABLED,TACKED,TAGGED,TAKING,TALKED,TAPPED,TASKED,TASTED,TEMPED,TENDED,TENURE,TERRAR,TEXTED,THAWED,THICKS,THINGS,THINKS,THIRDS,THROWS,TICKED,TIGHTS,TILING,TIPPED,TITLED,TOASTS,TODAYS,TONGUE,TOOLED,TOPICS,TORQUE,TOSSED,TOWELS,TRACED,TRADED,TRAILS,TRAINS,TRAVEL,TREATS,TRENDS,TRICKS,TRIPLE,TROOPS,TROPIC,TROUGH,TROWEL,TRUELY,TRUSTS,TRYING,TUMBLE,TUNING,TURTLE,TWISTS,TYPIST,UNIONS,UNIQUE,UNLESS,UNLOCK,UNPACK,UNSAFE,UNUSED,UPDATE,UPHILL,UPLOAD,UPTURN,UPWARD,URGENT,USEFUL,VACANT,VACUUM,VALLEY,VALUED,VALUES,VAULTS,VECTOR,VELVET,VENDOR,VERIFY,VERSUS,VESSEL,VICTOR,VIRTUE,VISIBLE,VOLUME,WALKER,WANTED,WARMTH,WEALTH,WIDGET,WINTER,WONDER,WORKER,WORTHY,YELLOW,YIELDS,ZOOMED`
  .split(",")
  .map((s) => s.trim().toUpperCase())
  .filter((w) => w.length === 6);

const all = [...new Set([...base, ...fill])];
let i = 0;
while (all.length < 365) {
  all.push(`KAI${String(i++).padStart(3, "0")}`);
}
const out = all.slice(0, 365);
const dir = dirname(fileURLToPath(import.meta.url));
const tsPath = join(dir, "../src/data/wordPuzzle365.ts");
writeFileSync(
  tsPath,
  `/** 365 unique 6-letter words for daily puzzle (rotates by day of year). */\nexport const WORD_LIST_365 = ${JSON.stringify(out)} as const;\n`,
  "utf8",
);
writeFileSync(join(dir, "words-365.json"), JSON.stringify(out), "utf8");
console.log("Wrote", out.length, "words");
